spring:
  profiles: local
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://phifsspdevdb.us.tgr.net:1433;databaseName=PHI_FSSP
    username : SVC_SQL_PHI_FSSP
    password: sA2Dgs2w@n3

---
spring :
  profiles: INT
  datasource:
    jndi-name: jdbc/TASTE-DS


---
spring:
  profiles: QA
  datasource:
    jndi-name: jdbc/TASTE-DS

---
spring:
  profiles: STAGE
  datasource:
    jndi-name: jdbc/TASTE-DS
---
spring:
  profiles: PROD
  datasource:
    jndi-name: jdbc/TASTE-DS
---
#Server Properties
server:
  port: 8092
  servlet:
    context-path: /tastepanel

#JPA Properties

spring:
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto : none

    properties:
      hibernate.dialect : org.hibernate.dialect.SQLServer2012Dialect
      org.hibernate.envers.store_data_at_delete : true
      hibernate.generate_statistics : false
      hibernate.format_sql: false
    show-sql: false


info:
  project:
    version: #project.version#

######################## log4j properties  #########################

logging:
  level:
    root: INFO
    org :
      springframework : INFO
      hibernate:
        SQL: INFO
        type: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"